language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: K9ItMhr+ulcM6W4UGj+UBmn3P40HWMhzFkWerDNq7Icl48HWbmYRQ6xlZ+2Iqicj9/eND8Ggbdq4EXjWjB9EgwV2NoYOEpIETIDc/OeJBE93WO2Jdk13LZNNzkU/TYDfb4ms45t5WwXhDFEDDBAEDDylGYGXZpRh+Nf/co0hGfA=
  - secure: XF8Zb54K3bUmsW0/gehnxVyGZIDCgqgJ3D1luxZWhS/LzCs5c1vF/WiOBaGUQ+PNE2KKFWiE5z+ohY2zkQM3ZDieBhDHOKG/BCn8RpFDqAZ+tJOKYwxh00meZOUAp1+bpqrV/G0+P5L6Ar5eSh1xgugkYRvbWHr7UaYBOQw97pM=
