language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
env:
  global:
    secure: HHxiUzUn5426CBHO88kaB7Yb47cx6IRXP+7Lj1Kl49TXSKtMW1H6QSRLaF676stdTlsxmpFYcaTzQQvTLhr7ySkTlG0cpGAzfvKoQiexdwy844pHbWonx659RV/CY76I4EOX+Y10Cbt46GELwnMp5FFrUfPtePAc6bh9ajkLcUM=
